### ISSUE TITLE
Difference between 2 brew taps

### ISSUE THREAD

**Issue by XuJiandong** [riscv-software-src/homebrew-riscv#120]
In README.md, it is:
```bash
brew tap riscv-software-src/riscv
```

But in CI, it is:
```bash
brew tap riscv/riscv
```

What is the difference between these 2 taps? Which one should we use?

**Comment by sbeamer** [comment]
Use `brew tap riscv-software-src/riscv`

`riscv/riscv` is the old name, and for now, it is still correctly redirecting.
