### ISSUE TITLE
Error MacOS monterey install riscv-tools

### ISSUE THREAD

**Issue by Toldblog** [riscv-software-src/homebrew-riscv#124]
when i run  `brew install riscv-tools` it show like this i dont know why the some Submodule (e.g binutils,...) don't have any content and i couldn't access these folder on the github repo also
==> Fetching dependencies for riscv/riscv/riscv-tools: riscv/riscv/riscv-gnu-toolchain, riscv/riscv/riscv-isa-sim and riscv/riscv/riscv-pk
==> Fetching riscv/riscv/riscv-gnu-toolchain
==> Cloning https://github.com/riscv/riscv-gnu-toolchain.git
Cloning into '/Users/apple/Library/Caches/Homebrew/riscv-gnu-toolchain--git'...
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'linux-headers/include/linux/netfilter/xt_CONNMARK.h'
  'linux-headers/include/linux/netfilter/xt_connmark.h'
  'linux-headers/include/linux/netfilter/xt_DSCP.h'
  'linux-headers/include/linux/netfilter/xt_dscp.h'
  'linux-headers/include/linux/netfilter/xt_MARK.h'
  'linux-headers/include/linux/netfilter/xt_mark.h'
  'linux-headers/include/linux/netfilter/xt_RATEEST.h'
  'linux-headers/include/linux/netfilter/xt_rateest.h'
  'linux-headers/include/linux/netfilter/xt_TCPMSS.h'
  'linux-headers/include/linux/netfilter/xt_tcpmss.h'
  'linux-headers/include/linux/netfilter_ipv4/ipt_ECN.h'
  'linux-headers/include/linux/netfilter_ipv4/ipt_ecn.h'
  'linux-headers/include/linux/netfilter_ipv4/ipt_TTL.h'
  'linux-headers/include/linux/netfilter_ipv4/ipt_ttl.h'
  'linux-headers/include/linux/netfilter_ipv6/ip6t_HL.h'
  'linux-headers/include/linux/netfilter_ipv6/ip6t_hl.h'
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Fetching riscv/riscv/riscv-isa-sim
==> Cloning https://github.com/riscv/riscv-isa-sim.git
Cloning into '/Users/apple/Library/Caches/Homebrew/riscv-isa-sim--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Fetching riscv/riscv/riscv-pk
==> Cloning https://github.com/riscv/riscv-pk.git
Cloning into '/Users/apple/Library/Caches/Homebrew/riscv-pk--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Fetching riscv/riscv/riscv-tools
==> Downloading https://github.com/riscv/riscv-tools/archive/homebrew.tar.gz
Already downloaded: /Users/apple/Library/Caches/Homebrew/downloads/5e080ac67877162e34a9e6701d88df637ec2f4abb27be9857918a142c6a3477e--riscv-tools-homebrew.tar.gz
==> Installing riscv-tools from riscv/riscv
==> Installing dependencies for riscv/riscv/riscv-tools: riscv/riscv/riscv-gnu-toolchain, riscv/riscv/riscv-isa-sim and riscv/riscv/riscv-pk
==> Installing riscv/riscv/riscv-tools dependency: riscv/riscv/riscv-gnu-toolchain
==> git submodule update --depth 1 --init --recursive newlib
==> git submodule update --depth 1 --init --recursive binutils
Last 15 lines from /Users/apple/Library/Logs/Homebrew/riscv-gnu-toolchain/02.git:

git
submodule
update
--depth
1
--init
--recursive
binutils

Submodule 'binutils' (https://sourceware.org/git/binutils-gdb.git) registered for path 'binutils'
Cloning into '/private/tmp/riscv-gnu-toolchain-20240221-81435-wevvd9/binutils'...
error: RPC failed; curl 55 Failed sending data to the peer
fatal: expected 'packfile'
fatal: Fetched in submodule path 'binutils', but it did not contain c7f28aad0c99d1d2fec4e52ebfa3735d90ceb8e9. Direct fetching of that commit failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/riscv/homebrew-riscv/issues

/usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:356:in `raise_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::API::ValidationFailedError)
	from /usr/local/Homebrew/Library/Homebrew/utils/github/api.rb:272:in `open_rest'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:182:in `search_results_items'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:36:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:62:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:502:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:497:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:553:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:143:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:131:in `<main>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2829:in `block in system': Failed executing: git submodule update --depth 1 --init --recursive binutils (BuildError)
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2765:in `open'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2765:in `system'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	from /usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11262/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
	from /usr/local/Homebrew/Library/Taps/riscv/homebrew-riscv/riscv-gnu-toolchain.rb:57:in `install'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:177:in `block (3 levels) in install'
	from /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:139:in `block (2 levels) in install'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:1407:in `block in brew'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2997:in `block (2 levels) in stage'
	from /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2996:in `block in stage'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:129:in `block (2 levels) in unpack'
	from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:121:in `chdir'
	from /usr/local/Homebrew/Library/Homebrew/download_strategy.rb:113:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:125:in `block in unpack'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `block in run'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `chdir'
	from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:75:in `run'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:226:in `stage_resource'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:124:in `unpack'
	from /usr/local/Homebrew/Library/Homebrew/resource.rb:98:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/lib/ruby/3.1.0/forwardable.rb:238:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:2976:in `stage'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:1400:in `brew'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:133:in `block in install'
	from /usr/local/Homebrew/Library/Homebrew/extend/kernel.rb:493:in `with_env'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:125:in `install'
	from /usr/local/Homebrew/Library/Homebrew/build.rb:229:in `<main>'

**Comment by sbeamer** [comment]
This seems like the same issue as #116.
