### ISSUE TITLE
sed: riscv-gcc/gcc/config.host: No such file or directory

### ISSUE THREAD

**Issue by GejinZ** [riscv-software-src/homebrew-riscv#60]
errors occur when `brew install riscv-tools`

![image](https://user-images.githubusercontent.com/20331327/120885649-940a0280-c61c-11eb-9ea2-4436f39c4e28.png)

I find this:
![image](https://user-images.githubusercontent.com/20331327/120885665-a5eba580-c61c-11eb-8655-c0c41c8608b2.png)

and my mac is not work on M1.

**Comment by GejinZ** [comment]
And my macOS version is 10.15.7 (19H524)

**Comment by ZonePG** [comment]
same error on my m1 macOS

**Comment by ZonePG** [comment]
I solved it, just delete riscv-gcc and `brew install riscv-tools` again.

**Comment by kalpesh2001** [comment]
Is there a plan to fix this issue? I tried to delete and reinstall with same error.

**Comment by sbeamer** [comment]
This seems to be M1-specific, so I am unable to reproduce. Would be grateful for any community help.
