### ISSUE TITLE
Missing RV32 Compiler

### ISSUE THREAD

**Issue by h5n1xp** [riscv-software-src/homebrew-riscv#74]
Apologies if this has already been addressed.

I have followed the instructions provided in the ReadMe and the build went without problem on my intel 2020 MBA. But the compiler installed is the RV64 variant.

My RISC-V machine only supports RV32I, is it possible to add RV32 support?

**Comment by h5n1xp** [comment]
Ok, I found another error in my build script causing errors.

Adding -march=rv32i gives the error:
cc1: error: requested ABI requires '-march' to subsume the 'D' extension.
cc1: error: ABI requires '-march=rv64'

Adding -march=rv32iD gives the error:
unsupported ISA subset 'D'

Adding -march=rv32id gives the error:
cc1: error: ABI requires '-march=rv64'

So I'm back to square one.

**Comment by h5n1xp** [comment]
Ok, setting -march=rv64id outputs mostly RV32I code, I can trap the few RV64I opcodes it does produce… So this is as close to a working solution as I can get for now.

**Comment by h5n1xp** [comment]
I think I have found a bug in the compiler.

when compiling the code bellow with -march=RV64id, it makes errors when doing multiplication

`
#include <stdint.h>

uint32_t p = 3;
uint32_t q = 20;



uint32_t main(){
    
uint32_t result = p * q;
    
    return 0;
}
`

The value returned in result is 63, not 60.

**Comment by h5n1xp** [comment]
the Compiler needs both options: -march=rv32id -mabi=ilp32 to compile to RV32I, but the linker complains that it can't link 32bit ELF files...

**Comment by sbeamer** [comment]
Yes, the -mabi flag is also necessary.

In your case, I believe the desired ISA extension combination (rv32id) is the issue. The multilib build doesn't have every combination, and the version I had in the most recent bottle seems to only include: rv32i, rv32iac, rv32im, rv32imac, rv32imafc, rv64imac, rv64gc.

When I try to build with your desired extension combination, I get the linking error. When I try one of the ones above, it works.

In your case, if you can't change your desired ISA, I recommend building from scratch and specifying the exact ISA and ABI you want at that point. This article seems to have a decent set of instructions: https://mindchasers.com/dev/rv-getting-started
