### ISSUE TITLE
brew install make error on M1 mac

### ISSUE THREAD

**Issue by z-wenbo** [riscv-software-src/homebrew-riscv#82]
In the make stages of the installation, I get this:
![Screen Shot 2022-01-18 at 3 40 32 PM](https://user-images.githubusercontent.com/89318903/149892200-aa34951c-40f3-4012-8865-f8b61214809f.jpg)
my Macbook is on M1, macOS 12.0.1

**Comment by sandeepwadhwa-ai** [comment]
Tried "brew install riscv-tools" on Mac M1. Does not work.

**Comment by Afrankie** [comment]
same error，on Mac AMD, macOS 11.3.1

**Comment by victoryang00** [comment]
Should work, it worked on my M1 Max. The build error seems to be the GitHub retrieving your identity API network issue.
