### ISSUE TITLE
submodule url protocol issue

### ISSUE THREAD

**Issue by z-wenbo** [riscv-software-src/homebrew-riscv#83]
![Screen Shot 2022-01-21 at 2 22 36 PM](https://user-images.githubusercontent.com/89318903/150510845-1b5fb65b-440c-43f9-9017-94cdab260865.jpg)

when cloning submodules, I notice that 2 different kinds of URL prefix are used: https:// and git:// . Since I am located in a country with internet restriction, I am only able to use `git clone` with https proxy. And during the cloning process, all the urls with https prefix are successfully cloned, but the two urls with git:// prefix failed. Can the developer maybe change them into https?

**Comment by sbeamer** [comment]
Unfortunately, those submodule paths are not set by this repository. I would follow up with the appropriate repository, and even open up a PR to make it easy for them.
