### ISSUE TITLE
brew install make error when installing riscv tool chain

### ISSUE THREAD

**Issue by fengmoh** [riscv-software-src/homebrew-riscv#84]
The error occurs when executing "make" after the commad. " ./configure --prefix=/usr/local/Cellar/riscv-gnu-toolchain/main --with-cmode"

The logs are like :
install: /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/po/zh_CN.gmo: No such file or directory

Full LOG:
==> Installing riscv-gnu-toolchain from riscv-software-src/riscv
==> sed -i .bak s/.*=host-darwin.o$// riscv-gcc/gcc/config.host
==> sed -i .bak s/.* x-darwin.$// riscv-gcc/gcc/config.host
==> ./configure --prefix=/usr/local/Cellar/riscv-gnu-toolchain/main --with-cmode
==> make
Last 15 lines from /Users/jiachengzheng/Library/Logs/Homebrew/riscv-gnu-toolchain/04.make:
installing /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/po/vi.gmo as /usr/local/Cellar/riscv-gnu-toolchain/main/share/locale/vi/LC_MESSAGES/opcodes.mo
install: /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/po/zh_CN.gmo: No such file or directory
installing /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/po/zh_CN.gmo as /usr/local/Cellar/riscv-gnu-toolchain/main/share/locale/zh_CN/LC_MESSAGES/opcodes.mo
if test "opcodes" = "gettext"; then \
	  if test -r /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/../mkinstalldirs; then \
	    /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/../mkinstalldirs /usr/local/Cellar/riscv-gnu-toolchain/main/share/gettext/po; \
	  else \
	    /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/mkinstalldirs /usr/local/Cellar/riscv-gnu-toolchain/main/share/gettext/po; \
	  fi; \
	  /usr/bin/install -c -m 644 /private/tmp/riscv-gnu-toolchain-20220206-11224-b2o7s/riscv-gdb/opcodes/po/Makefile.in.in \
			  /usr/local/Cellar/riscv-gnu-toolchain/main/share/gettext/po/Makefile.in.in; \
	else \
	  : ; \
	fi
mkdir -p stamps/ && touch stamps/build-gdb-newlib

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/riscv-software-src/homebrew-riscv/issues

**Comment by sbeamer** [comment]
With the information provided, this is hard to diagnose. Please included any additional information about the error or your system to help.
