### ISSUE TITLE
fatal: Unable to find current revision in submodule path 'glibc'

### ISSUE THREAD

**Issue by MrZLeo** [riscv-software-src/homebrew-riscv#87]
I got error said:

```
fatal: Unable to find current revision in submodule path 'glibc'
Error: riscv-tools: Failed to download resource "riscv-gnu-toolchain"
Failure while executing; `git submodule update --init --recursive` exited with 128. Here's the output:
fatal: Unable to find current revision in submodule path 'glibc'
```

I don't know how to fix it. Anyone can help?

My device: MacBook Pro m1 2020, macOS 12, Xcode 13.4

I use command:

```
brew tap riscv-software-src/riscv
brew install riscv-tools
```

**Comment by Sped0n** [comment]
you can try to clone riscv-gnu-toolchain directly from GitHub, then copy all the files in the folder to where your brew cache is, like```/Users/spedon/Library/Caches/Homebrew/riscv-gnu-toolchain--git```.

**Comment by sbeamer** [comment]
The recent change (3a5cb0c811f7b7312a243fb27675a53264db2b89) to reduce the number of submodules pulled in may help with this.
